// <auto-generated />
using Memento.Movies.Shared.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace Memento.Movies.Shared.Migrations
{
	[DbContext(typeof(MovieContext))]
	[Migration("20200520150107_InitialMigration")]
	internal partial class InitialMigration
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
			#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "3.1.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 128)
				.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("Memento.Movies.Shared.Database.Models.Movies.Movie", b =>
			{
				b.Property<long>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("bigint")
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<DateTime>("CreatedAt")
					.HasColumnType("datetime2");

				b.Property<long>("CreatedBy")
					.HasColumnType("bigint");

				b.Property<string>("Genre")
					.IsRequired()
					.HasColumnType("nvarchar(50)")
					.HasMaxLength(50);

				b.Property<DateTime>("ReleaseDate")
					.HasColumnType("datetime2");

				b.Property<string>("Title")
					.IsRequired()
					.HasColumnType("nvarchar(250)")
					.HasMaxLength(250);

				b.Property<DateTime?>("UpdatedAt")
					.HasColumnType("datetime2");

				b.Property<long?>("UpdatedBy")
					.HasColumnType("bigint");

				b.HasKey("Id");

				b.HasIndex("Genre");

				b.HasIndex("ReleaseDate");

				b.HasIndex("Title")
					.IsUnique();

				b.ToTable("Movies");
			});
			#pragma warning restore 612, 618
		}
	}
}