//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memento.Movies.Shared.Resources
{
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class SharedResources
	{
		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal SharedResources()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Memento.Movies.Shared.Resources.SharedResources", typeof(SharedResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Create {0}.
		/// </summary>
		public static string BREADCRUMB_CREATE_HEADER
		{
			get
			{
				return ResourceManager.GetString("BREADCRUMB_CREATE_HEADER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Create.
		/// </summary>
		public static string BREADCRUMB_CREATE_LINK_LABEL
		{
			get
			{
				return ResourceManager.GetString("BREADCRUMB_CREATE_LINK_LABEL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0}.
		/// </summary>
		public static string BREADCRUMB_DETAIL_HEADER
		{
			get
			{
				return ResourceManager.GetString("BREADCRUMB_DETAIL_HEADER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Detail.
		/// </summary>
		public static string BREADCRUMB_DETAIL_LINK_LABEL
		{
			get
			{
				return ResourceManager.GetString("BREADCRUMB_DETAIL_LINK_LABEL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0}.
		/// </summary>
		public static string BREADCRUMB_LIST_HEADER
		{
			get
			{
				return ResourceManager.GetString("BREADCRUMB_LIST_HEADER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to {0}.
		/// </summary>
		public static string BREADCRUMB_LIST_LINK_LABEL
		{
			get
			{
				return ResourceManager.GetString("BREADCRUMB_LIST_LINK_LABEL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update {0}..
		/// </summary>
		public static string BREADCRUMB_UPDATE_HEADER
		{
			get
			{
				return ResourceManager.GetString("BREADCRUMB_UPDATE_HEADER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		public static string BREADCRUMB_UPDATE_LINK_LABEL
		{
			get
			{
				return ResourceManager.GetString("BREADCRUMB_UPDATE_LINK_LABEL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cancel.
		/// </summary>
		public static string BUTTON_CANCEL
		{
			get
			{
				return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Confirm.
		/// </summary>
		public static string BUTTON_CONFIRM
		{
			get
			{
				return ResourceManager.GetString("BUTTON_CONFIRM", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Create.
		/// </summary>
		public static string BUTTON_CREATE
		{
			get
			{
				return ResourceManager.GetString("BUTTON_CREATE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		public static string BUTTON_DELETE
		{
			get
			{
				return ResourceManager.GetString("BUTTON_DELETE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Discard.
		/// </summary>
		public static string BUTTON_DISCARD_CHANGES
		{
			get
			{
				return ResourceManager.GetString("BUTTON_DISCARD_CHANGES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Save.
		/// </summary>
		public static string BUTTON_SAVE_CHANGES
		{
			get
			{
				return ResourceManager.GetString("BUTTON_SAVE_CHANGES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		public static string BUTTON_UPDATE
		{
			get
			{
				return ResourceManager.GetString("BUTTON_UPDATE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to View.
		/// </summary>
		public static string BUTTON_VIEW
		{
			get
			{
				return ResourceManager.GetString("BUTTON_VIEW", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The creation was completed successfully..
		/// </summary>
		public static string CONTROLLER_CREATE_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_CREATE_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The deletion was completed successfully..
		/// </summary>
		public static string CONTROLLER_DELETE_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_DELETE_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The listing was obtained successfully..
		/// </summary>
		public static string CONTROLLER_GET_ALL_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_GET_ALL_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The detail was obtained successfully..
		/// </summary>
		public static string CONTROLLER_GET_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_GET_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The update was completed successfully..
		/// </summary>
		public static string CONTROLLER_UPDATE_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_UPDATE_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The field &apos;{0}&apos; already exists..
		/// </summary>
		public static string ERROR_DUPLICATE_FIELD
		{
			get
			{
				return ResourceManager.GetString("ERROR_DUPLICATE_FIELD", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The field &apos;{0}&apos; is invalid..
		/// </summary>
		public static string ERROR_INVALID_FIELD
		{
			get
			{
				return ResourceManager.GetString("ERROR_INVALID_FIELD", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to An error occured while loading the page. Please try again later..
		/// </summary>
		public static string ERROR_LOADING
		{
			get
			{
				return ResourceManager.GetString("ERROR_LOADING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The {0} does not exist..
		/// </summary>
		public static string ERROR_NOT_FOUND
		{
			get
			{
				return ResourceManager.GetString("ERROR_NOT_FOUND", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to An error unexpected error occurred. Please try again later..
		/// </summary>
		public static string ERROR_UNEXPECTED
		{
			get
			{
				return ResourceManager.GetString("ERROR_UNEXPECTED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Filter.
		/// </summary>
		public static string FILTER_HEADING
		{
			get
			{
				return ResourceManager.GetString("FILTER_HEADING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Reset.
		/// </summary>
		public static string FILTER_RESET_BUTTON
		{
			get
			{
				return ResourceManager.GetString("FILTER_RESET_BUTTON", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Search.
		/// </summary>
		public static string FILTER_SEARCH_BUTTON
		{
			get
			{
				return ResourceManager.GetString("FILTER_SEARCH_BUTTON", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Preview.
		/// </summary>
		public static string FORM_IMAGE_PREVIEW
		{
			get
			{
				return ResourceManager.GetString("FORM_IMAGE_PREVIEW", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The form has invalid fields..
		/// </summary>
		public static string FORM_INVALID_FIELDS
		{
			get
			{
				return ResourceManager.GetString("FORM_INVALID_FIELDS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Preview.
		/// </summary>
		public static string FORM_MARKDOWN_PREVIEW
		{
			get
			{
				return ResourceManager.GetString("FORM_MARKDOWN_PREVIEW", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Loading....
		/// </summary>
		public static string FORM_TYPEAHEAD_LOADING
		{
			get
			{
				return ResourceManager.GetString("FORM_TYPEAHEAD_LOADING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No records were found.
		/// </summary>
		public static string FORM_TYPEAHEAD_NOT_FOUND
		{
			get
			{
				return ResourceManager.GetString("FORM_TYPEAHEAD_NOT_FOUND", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to In Theaters.
		/// </summary>
		public static string GENERIC_IN_THEATERS
		{
			get
			{
				return ResourceManager.GetString("GENERIC_IN_THEATERS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Loading.
		/// </summary>
		public static string GENERIC_LOADING
		{
			get
			{
				return ResourceManager.GetString("GENERIC_LOADING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No records were found.
		/// </summary>
		public static string GENERIC_NO_RECORDS_FOUND
		{
			get
			{
				return ResourceManager.GetString("GENERIC_NO_RECORDS_FOUND", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Upcoming Releases.
		/// </summary>
		public static string GENERIC_UPCOMING_RELEASES
		{
			get
			{
				return ResourceManager.GetString("GENERIC_UPCOMING_RELEASES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Genre.
		/// </summary>
		public static string GENRE
		{
			get
			{
				return ResourceManager.GetString("GENRE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string GENRE_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("GENRE_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string GENRE_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("GENRE_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string GENRE_ID
		{
			get
			{
				return ResourceManager.GetString("GENRE_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movies.
		/// </summary>
		public static string GENRE_MOVIES
		{
			get
			{
				return ResourceManager.GetString("GENRE_MOVIES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string GENRE_NAME
		{
			get
			{
				return ResourceManager.GetString("GENRE_NAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ascending.
		/// </summary>
		public static string GENRE_ORDER_ASCENDING
		{
			get
			{
				return ResourceManager.GetString("GENRE_ORDER_ASCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Descending.
		/// </summary>
		public static string GENRE_ORDER_DESCENDING
		{
			get
			{
				return ResourceManager.GetString("GENRE_ORDER_DESCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Genres.
		/// </summary>
		public static string GENRE_PLURAL
		{
			get
			{
				return ResourceManager.GetString("GENRE_PLURAL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string GENRE_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("GENRE_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string GENRE_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("GENRE_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Home.
		/// </summary>
		public static string HOME
		{
			get
			{
				return ResourceManager.GetString("HOME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to delete this {0}?.
		/// </summary>
		public static string MODAL_DELETE_BODY
		{
			get
			{
				return ResourceManager.GetString("MODAL_DELETE_BODY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete {0}.
		/// </summary>
		public static string MODAL_DELETE_TITLE
		{
			get
			{
				return ResourceManager.GetString("MODAL_DELETE_TITLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to discard your changes?.
		/// </summary>
		public static string MODAL_DISCARD_CHANGES_BODY
		{
			get
			{
				return ResourceManager.GetString("MODAL_DISCARD_CHANGES_BODY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Discard changes.
		/// </summary>
		public static string MODAL_DISCARD_CHANGES_TITLE
		{
			get
			{
				return ResourceManager.GetString("MODAL_DISCARD_CHANGES_TITLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to save your changes?.
		/// </summary>
		public static string MODAL_SAVE_CHANGES_BODY
		{
			get
			{
				return ResourceManager.GetString("MODAL_SAVE_CHANGES_BODY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Save changes.
		/// </summary>
		public static string MODAL_SAVE_CHANGES_TITLE
		{
			get
			{
				return ResourceManager.GetString("MODAL_SAVE_CHANGES_TITLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movie.
		/// </summary>
		public static string MOVIE
		{
			get
			{
				return ResourceManager.GetString("MOVIE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Actors.
		/// </summary>
		public static string MOVIE_ACTORS
		{
			get
			{
				return ResourceManager.GetString("MOVIE_ACTORS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string MOVIE_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("MOVIE_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string MOVIE_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("MOVIE_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Directors.
		/// </summary>
		public static string MOVIE_DIRECTORS
		{
			get
			{
				return ResourceManager.GetString("MOVIE_DIRECTORS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Genres.
		/// </summary>
		public static string MOVIE_GENRES
		{
			get
			{
				return ResourceManager.GetString("MOVIE_GENRES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string MOVIE_ID
		{
			get
			{
				return ResourceManager.GetString("MOVIE_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to In Theaters.
		/// </summary>
		public static string MOVIE_INTHEATERS
		{
			get
			{
				return ResourceManager.GetString("MOVIE_INTHEATERS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to In Theaters.
		/// </summary>
		public static string MOVIE_INTHEATERS_CHECKED
		{
			get
			{
				return ResourceManager.GetString("MOVIE_INTHEATERS_CHECKED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Not In Theaters.
		/// </summary>
		public static string MOVIE_INTHEATERS_UNCHECKED
		{
			get
			{
				return ResourceManager.GetString("MOVIE_INTHEATERS_UNCHECKED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string MOVIE_NAME
		{
			get
			{
				return ResourceManager.GetString("MOVIE_NAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ascending.
		/// </summary>
		public static string MOVIE_ORDER_ASCENDING
		{
			get
			{
				return ResourceManager.GetString("MOVIE_ORDER_ASCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Descending.
		/// </summary>
		public static string MOVIE_ORDER_DESCENDING
		{
			get
			{
				return ResourceManager.GetString("MOVIE_ORDER_DESCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Persons.
		/// </summary>
		public static string MOVIE_PERSONS
		{
			get
			{
				return ResourceManager.GetString("MOVIE_PERSONS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Picture.
		/// </summary>
		public static string MOVIE_PICTURE
		{
			get
			{
				return ResourceManager.GetString("MOVIE_PICTURE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Picture (URL).
		/// </summary>
		public static string MOVIE_PICTUREURL
		{
			get
			{
				return ResourceManager.GetString("MOVIE_PICTUREURL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movies.
		/// </summary>
		public static string MOVIE_PLURAL
		{
			get
			{
				return ResourceManager.GetString("MOVIE_PLURAL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Released After.
		/// </summary>
		public static string MOVIE_RELEASEDAFTER
		{
			get
			{
				return ResourceManager.GetString("MOVIE_RELEASEDAFTER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Release Date.
		/// </summary>
		public static string MOVIE_RELEASEDATE
		{
			get
			{
				return ResourceManager.GetString("MOVIE_RELEASEDATE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Released Before.
		/// </summary>
		public static string MOVIE_RELEASEDBEFORE
		{
			get
			{
				return ResourceManager.GetString("MOVIE_RELEASEDBEFORE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Summary.
		/// </summary>
		public static string MOVIE_SUMMARY
		{
			get
			{
				return ResourceManager.GetString("MOVIE_SUMMARY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Trailer (URL).
		/// </summary>
		public static string MOVIE_TRAILERURL
		{
			get
			{
				return ResourceManager.GetString("MOVIE_TRAILERURL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string MOVIE_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("MOVIE_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string MOVIE_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("MOVIE_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Writers.
		/// </summary>
		public static string MOVIE_WRITERS
		{
			get
			{
				return ResourceManager.GetString("MOVIE_WRITERS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string MOVIEGENRE_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string MOVIEGENRE_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Genre.
		/// </summary>
		public static string MOVIEGENRE_GENRE
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_GENRE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Genre Identifier.
		/// </summary>
		public static string MOVIEGENRE_GENREID
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_GENREID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string MOVIEGENRE_ID
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movie.
		/// </summary>
		public static string MOVIEGENRE_MOVIE
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_MOVIE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movie Identifier.
		/// </summary>
		public static string MOVIEGENRE_MOVIEID
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_MOVIEID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string MOVIEGENRE_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string MOVIEGENRE_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string MOVIEPERSON_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string MOVIEPERSON_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string MOVIEPERSON_ID
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movie.
		/// </summary>
		public static string MOVIEPERSON_MOVIE
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_MOVIE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movie Identifier.
		/// </summary>
		public static string MOVIEPERSON_MOVIEID
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_MOVIEID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Person.
		/// </summary>
		public static string MOVIEPERSON_PERSON
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_PERSON", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Person Identifier.
		/// </summary>
		public static string MOVIEPERSON_PERSONID
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_PERSONID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Role.
		/// </summary>
		public static string MOVIEPERSON_ROLE
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_ROLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string MOVIEPERSON_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string MOVIEPERSON_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Actor.
		/// </summary>
		public static string MOVIEPERSONROLE_ACTOR
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSONROLE_ACTOR", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Director.
		/// </summary>
		public static string MOVIEPERSONROLE_DIRECTOR
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSONROLE_DIRECTOR", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Writer.
		/// </summary>
		public static string MOVIEPERSONROLE_WRITER
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSONROLE_WRITER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Person.
		/// </summary>
		public static string PERSON
		{
			get
			{
				return ResourceManager.GetString("PERSON", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Biography.
		/// </summary>
		public static string PERSON_BIOGRAPHY
		{
			get
			{
				return ResourceManager.GetString("PERSON_BIOGRAPHY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Birth Date.
		/// </summary>
		public static string PERSON_BIRTHDATE
		{
			get
			{
				return ResourceManager.GetString("PERSON_BIRTHDATE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Born After.
		/// </summary>
		public static string PERSON_BORNAFTER
		{
			get
			{
				return ResourceManager.GetString("PERSON_BORNAFTER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Born Before.
		/// </summary>
		public static string PERSON_BORNBEFORE
		{
			get
			{
				return ResourceManager.GetString("PERSON_BORNBEFORE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string PERSON_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("PERSON_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string PERSON_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("PERSON_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string PERSON_ID
		{
			get
			{
				return ResourceManager.GetString("PERSON_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movies.
		/// </summary>
		public static string PERSON_MOVIES
		{
			get
			{
				return ResourceManager.GetString("PERSON_MOVIES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string PERSON_NAME
		{
			get
			{
				return ResourceManager.GetString("PERSON_NAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ascending.
		/// </summary>
		public static string PERSON_ORDER_ASCENDING
		{
			get
			{
				return ResourceManager.GetString("PERSON_ORDER_ASCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Descending.
		/// </summary>
		public static string PERSON_ORDER_DESCENDING
		{
			get
			{
				return ResourceManager.GetString("PERSON_ORDER_DESCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Picture.
		/// </summary>
		public static string PERSON_PICTURE
		{
			get
			{
				return ResourceManager.GetString("PERSON_PICTURE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Picture (URL).
		/// </summary>
		public static string PERSON_PICTUREURL
		{
			get
			{
				return ResourceManager.GetString("PERSON_PICTUREURL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Persons.
		/// </summary>
		public static string PERSON_PLURAL
		{
			get
			{
				return ResourceManager.GetString("PERSON_PLURAL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string PERSON_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("PERSON_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string PERSON_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("PERSON_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Role.
		/// </summary>
		public static string ROLE
		{
			get
			{
				return ResourceManager.GetString("ROLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Concurrency Stamp.
		/// </summary>
		public static string ROLE_CONCURRENCYSTAMP
		{
			get
			{
				return ResourceManager.GetString("ROLE_CONCURRENCYSTAMP", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string ROLE_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("ROLE_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string ROLE_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("ROLE_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enabled.
		/// </summary>
		public static string ROLE_ENABLED
		{
			get
			{
				return ResourceManager.GetString("ROLE_ENABLED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enabled.
		/// </summary>
		public static string ROLE_ENABLED_CHECKED
		{
			get
			{
				return ResourceManager.GetString("ROLE_ENABLED_CHECKED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Disabled.
		/// </summary>
		public static string ROLE_ENABLED_UNCHECKED
		{
			get
			{
				return ResourceManager.GetString("ROLE_ENABLED_UNCHECKED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string ROLE_ID
		{
			get
			{
				return ResourceManager.GetString("ROLE_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string ROLE_NAME
		{
			get
			{
				return ResourceManager.GetString("ROLE_NAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ascending.
		/// </summary>
		public static string ROLE_ORDER_ASCENDING
		{
			get
			{
				return ResourceManager.GetString("ROLE_ORDER_ASCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Descending.
		/// </summary>
		public static string ROLE_ORDER_DESCENDING
		{
			get
			{
				return ResourceManager.GetString("ROLE_ORDER_DESCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claims.
		/// </summary>
		public static string ROLE_ROLECLAIMS
		{
			get
			{
				return ResourceManager.GetString("ROLE_ROLECLAIMS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Users.
		/// </summary>
		public static string ROLE_ROLEUSERS
		{
			get
			{
				return ResourceManager.GetString("ROLE_ROLEUSERS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string ROLE_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("ROLE_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string ROLE_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("ROLE_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claim.
		/// </summary>
		public static string ROLECLAIM
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claim Type.
		/// </summary>
		public static string ROLECLAIM_CLAIMTYPE
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_CLAIMTYPE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claim Value.
		/// </summary>
		public static string ROLECLAIM_CLAIMVALUE
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_CLAIMVALUE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string ROLECLAIM_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string ROLECLAIM_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string ROLECLAIM_ID
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Role.
		/// </summary>
		public static string ROLECLAIM_ROLE
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_ROLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Role Identifier.
		/// </summary>
		public static string ROLECLAIM_ROLEID
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_ROLEID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string ROLECLAIM_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string ROLECLAIM_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("ROLECLAIM_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User.
		/// </summary>
		public static string USER
		{
			get
			{
				return ResourceManager.GetString("USER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Access Failed Count.
		/// </summary>
		public static string USER_ACCESSFAILEDCOUNT
		{
			get
			{
				return ResourceManager.GetString("USER_ACCESSFAILEDCOUNT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Concurrency Stamp.
		/// </summary>
		public static string USER_CONCURRENCYSTAMP
		{
			get
			{
				return ResourceManager.GetString("USER_CONCURRENCYSTAMP", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string USER_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("USER_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string USER_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("USER_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Email.
		/// </summary>
		public static string USER_EMAIL
		{
			get
			{
				return ResourceManager.GetString("USER_EMAIL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Email Confirmed.
		/// </summary>
		public static string USER_EMAILCONFIRMED
		{
			get
			{
				return ResourceManager.GetString("USER_EMAILCONFIRMED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enabled.
		/// </summary>
		public static string USER_ENABLED
		{
			get
			{
				return ResourceManager.GetString("USER_ENABLED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Enabled.
		/// </summary>
		public static string USER_ENABLED_CHECKED
		{
			get
			{
				return ResourceManager.GetString("USER_ENABLED_CHECKED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Disabled.
		/// </summary>
		public static string USER_ENABLED_UNCHECKED
		{
			get
			{
				return ResourceManager.GetString("USER_ENABLED_UNCHECKED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string USER_ID
		{
			get
			{
				return ResourceManager.GetString("USER_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lockout Enabled.
		/// </summary>
		public static string USER_LOCKOUTENABLED
		{
			get
			{
				return ResourceManager.GetString("USER_LOCKOUTENABLED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Lockout Ends At.
		/// </summary>
		public static string USER_LOCKOUTEND
		{
			get
			{
				return ResourceManager.GetString("USER_LOCKOUTEND", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Ascending.
		/// </summary>
		public static string USER_ORDER_ASCENDING
		{
			get
			{
				return ResourceManager.GetString("USER_ORDER_ASCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Descending.
		/// </summary>
		public static string USER_ORDER_DESCENDING
		{
			get
			{
				return ResourceManager.GetString("USER_ORDER_DESCENDING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Password Hash.
		/// </summary>
		public static string USER_PASSWORDHASH
		{
			get
			{
				return ResourceManager.GetString("USER_PASSWORDHASH", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Phone Number.
		/// </summary>
		public static string USER_PHONENUMBER
		{
			get
			{
				return ResourceManager.GetString("USER_PHONENUMBER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Phone Number Confirmed.
		/// </summary>
		public static string USER_PHONENUMBERCONFIRMED
		{
			get
			{
				return ResourceManager.GetString("USER_PHONENUMBERCONFIRMED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Password Hash.
		/// </summary>
		public static string USER_SECURITYSTAMP
		{
			get
			{
				return ResourceManager.GetString("USER_SECURITYSTAMP", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Two Factor Enabled.
		/// </summary>
		public static string USER_TWOFACTORENABLED
		{
			get
			{
				return ResourceManager.GetString("USER_TWOFACTORENABLED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string USER_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("USER_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string USER_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("USER_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claims.
		/// </summary>
		public static string USER_USERCLAIMS
		{
			get
			{
				return ResourceManager.GetString("USER_USERCLAIMS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Logins.
		/// </summary>
		public static string USER_USERLOGINS
		{
			get
			{
				return ResourceManager.GetString("USER_USERLOGINS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Username.
		/// </summary>
		public static string USER_USERNAME
		{
			get
			{
				return ResourceManager.GetString("USER_USERNAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Roles.
		/// </summary>
		public static string USER_USERROLES
		{
			get
			{
				return ResourceManager.GetString("USER_USERROLES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Tokens.
		/// </summary>
		public static string USER_USERTOKENS
		{
			get
			{
				return ResourceManager.GetString("USER_USERTOKENS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claim.
		/// </summary>
		public static string USERCLAIM
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claim Type.
		/// </summary>
		public static string USERCLAIM_CLAIMTYPE
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_CLAIMTYPE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Claim Value.
		/// </summary>
		public static string USERCLAIM_CLAIMVALUE
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_CLAIMVALUE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string USERCLAIM_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string USERCLAIM_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string USERCLAIM_ID
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string USERCLAIM_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string USERCLAIM_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User.
		/// </summary>
		public static string USERCLAIM_USER
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_USER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User Identifier.
		/// </summary>
		public static string USERCLAIM_USERID
		{
			get
			{
				return ResourceManager.GetString("USERCLAIM_USERID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Login.
		/// </summary>
		public static string USERLOGIN
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string USERLOGIN_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string USERLOGIN_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Provider.
		/// </summary>
		public static string USERLOGIN_LOGINPROVIDER
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_LOGINPROVIDER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Provider Name.
		/// </summary>
		public static string USERLOGIN_PROVIDERDISPLAYNAME
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_PROVIDERDISPLAYNAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Provider Key.
		/// </summary>
		public static string USERLOGIN_PROVIDERKEY
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_PROVIDERKEY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string USERLOGIN_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string USERLOGIN_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User.
		/// </summary>
		public static string USERLOGIN_USER
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_USER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User Identifier.
		/// </summary>
		public static string USERLOGIN_USERID
		{
			get
			{
				return ResourceManager.GetString("USERLOGIN_USERID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User Role.
		/// </summary>
		public static string USERROLE
		{
			get
			{
				return ResourceManager.GetString("USERROLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string USERROLE_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERROLE_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string USERROLE_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERROLE_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Role.
		/// </summary>
		public static string USERROLE_ROLE
		{
			get
			{
				return ResourceManager.GetString("USERROLE_ROLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Role Identifier.
		/// </summary>
		public static string USERROLE_ROLEID
		{
			get
			{
				return ResourceManager.GetString("USERROLE_ROLEID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string USERROLE_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERROLE_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string USERROLE_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERROLE_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User.
		/// </summary>
		public static string USERROLE_USER
		{
			get
			{
				return ResourceManager.GetString("USERROLE_USER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User Identifier.
		/// </summary>
		public static string USERROLE_USERID
		{
			get
			{
				return ResourceManager.GetString("USERROLE_USERID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Login.
		/// </summary>
		public static string USERTOKEN
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string USERTOKEN_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string USERTOKEN_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Provider.
		/// </summary>
		public static string USERTOKEN_LOGINPROVIDER
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_LOGINPROVIDER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string USERTOKEN_NAME
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_NAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string USERTOKEN_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string USERTOKEN_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User.
		/// </summary>
		public static string USERTOKEN_USER
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_USER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to User Identifier.
		/// </summary>
		public static string USERTOKEN_USERID
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_USERID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Value.
		/// </summary>
		public static string USERTOKEN_VALUE
		{
			get
			{
				return ResourceManager.GetString("USERTOKEN_VALUE", resourceCulture);
			}
		}
	}
}
