//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Memento.Movies.Shared.Resources
{
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class SharedResources
	{
		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal SharedResources()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Memento.Movies.Shared.Resources.SharedResources", typeof(SharedResources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Cancel.
		/// </summary>
		public static string BUTTON_CANCEL
		{
			get
			{
				return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Confirm.
		/// </summary>
		public static string BUTTON_CONFIRM
		{
			get
			{
				return ResourceManager.GetString("BUTTON_CONFIRM", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Create.
		/// </summary>
		public static string BUTTON_CREATE
		{
			get
			{
				return ResourceManager.GetString("BUTTON_CREATE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		public static string BUTTON_DELETE
		{
			get
			{
				return ResourceManager.GetString("BUTTON_DELETE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Discard.
		/// </summary>
		public static string BUTTON_DISCARD_CHANGES
		{
			get
			{
				return ResourceManager.GetString("BUTTON_DISCARD_CHANGES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Save.
		/// </summary>
		public static string BUTTON_SAVE_CHANGES
		{
			get
			{
				return ResourceManager.GetString("BUTTON_SAVE_CHANGES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Update.
		/// </summary>
		public static string BUTTON_UPDATE
		{
			get
			{
				return ResourceManager.GetString("BUTTON_UPDATE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to View.
		/// </summary>
		public static string BUTTON_VIEW
		{
			get
			{
				return ResourceManager.GetString("BUTTON_VIEW", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The {0} was created successfully..
		/// </summary>
		public static string CONTROLLER_CREATE_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_CREATE_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The {0} was deleted successfully..
		/// </summary>
		public static string CONTROLLER_DELETE_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_DELETE_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The {0} were obtained successfully..
		/// </summary>
		public static string CONTROLLER_GET_ALL_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_GET_ALL_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The {0} was obtained successfully..
		/// </summary>
		public static string CONTROLLER_GET_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_GET_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The {0} was updated successfully..
		/// </summary>
		public static string CONTROLLER_UPDATE_SUCCESSFUL
		{
			get
			{
				return ResourceManager.GetString("CONTROLLER_UPDATE_SUCCESSFUL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The field &apos;{0}&apos; already exists..
		/// </summary>
		public static string ERROR_DUPLICATE_FIELD
		{
			get
			{
				return ResourceManager.GetString("ERROR_DUPLICATE_FIELD", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The field &apos;{0}&apos; is invalid..
		/// </summary>
		public static string ERROR_INVALID_FIELD
		{
			get
			{
				return ResourceManager.GetString("ERROR_INVALID_FIELD", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to An error occured while loading the page. Please try again later..
		/// </summary>
		public static string ERROR_LOADING
		{
			get
			{
				return ResourceManager.GetString("ERROR_LOADING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The {0} does not exist..
		/// </summary>
		public static string ERROR_NOT_FOUND
		{
			get
			{
				return ResourceManager.GetString("ERROR_NOT_FOUND", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to An error unexpected error occurred. Please try again later..
		/// </summary>
		public static string ERROR_UNEXPECTED
		{
			get
			{
				return ResourceManager.GetString("ERROR_UNEXPECTED", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Preview.
		/// </summary>
		public static string FORM_IMAGE_PREVIEW
		{
			get
			{
				return ResourceManager.GetString("FORM_IMAGE_PREVIEW", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to The form has invalid fields..
		/// </summary>
		public static string FORM_INVALID_FIELDS
		{
			get
			{
				return ResourceManager.GetString("FORM_INVALID_FIELDS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Preview.
		/// </summary>
		public static string FORM_MARKDOWN_PREVIEW
		{
			get
			{
				return ResourceManager.GetString("FORM_MARKDOWN_PREVIEW", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Loading....
		/// </summary>
		public static string FORM_TYPEAHEAD_LOADING
		{
			get
			{
				return ResourceManager.GetString("FORM_TYPEAHEAD_LOADING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No records were found.
		/// </summary>
		public static string FORM_TYPEAHEAD_NOT_FOUND
		{
			get
			{
				return ResourceManager.GetString("FORM_TYPEAHEAD_NOT_FOUND", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Loading.
		/// </summary>
		public static string GENERIC_LOADING
		{
			get
			{
				return ResourceManager.GetString("GENERIC_LOADING", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to No records were found.
		/// </summary>
		public static string GENERIC_NO_RECORDS_FOUND
		{
			get
			{
				return ResourceManager.GetString("GENERIC_NO_RECORDS_FOUND", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Genre.
		/// </summary>
		public static string GENRE
		{
			get
			{
				return ResourceManager.GetString("GENRE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string GENRE_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("GENRE_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string GENRE_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("GENRE_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string GENRE_ID
		{
			get
			{
				return ResourceManager.GetString("GENRE_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movies.
		/// </summary>
		public static string GENRE_MOVIES
		{
			get
			{
				return ResourceManager.GetString("GENRE_MOVIES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string GENRE_NAME
		{
			get
			{
				return ResourceManager.GetString("GENRE_NAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Genres.
		/// </summary>
		public static string GENRE_PLURAL
		{
			get
			{
				return ResourceManager.GetString("GENRE_PLURAL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string GENRE_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("GENRE_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string GENRE_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("GENRE_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to delete this {0}?.
		/// </summary>
		public static string MODAL_DELETE_BODY
		{
			get
			{
				return ResourceManager.GetString("MODAL_DELETE_BODY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Delete {0}.
		/// </summary>
		public static string MODAL_DELETE_TITLE
		{
			get
			{
				return ResourceManager.GetString("MODAL_DELETE_TITLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to discard your changes?.
		/// </summary>
		public static string MODAL_DISCARD_CHANGES_BODY
		{
			get
			{
				return ResourceManager.GetString("MODAL_DISCARD_CHANGES_BODY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Discard changes.
		/// </summary>
		public static string MODAL_DISCARD_CHANGES_TITLE
		{
			get
			{
				return ResourceManager.GetString("MODAL_DISCARD_CHANGES_TITLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to save your changes?.
		/// </summary>
		public static string MODAL_SAVE_CHANGES_BODY
		{
			get
			{
				return ResourceManager.GetString("MODAL_SAVE_CHANGES_BODY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Save changes.
		/// </summary>
		public static string MODAL_SAVE_CHANGES_TITLE
		{
			get
			{
				return ResourceManager.GetString("MODAL_SAVE_CHANGES_TITLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movie.
		/// </summary>
		public static string MOVIE
		{
			get
			{
				return ResourceManager.GetString("MOVIE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Actors.
		/// </summary>
		public static string MOVIE_ACTORS
		{
			get
			{
				return ResourceManager.GetString("MOVIE_ACTORS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string MOVIE_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("MOVIE_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string MOVIE_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("MOVIE_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Directors.
		/// </summary>
		public static string MOVIE_DIRECTORS
		{
			get
			{
				return ResourceManager.GetString("MOVIE_DIRECTORS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Genres.
		/// </summary>
		public static string MOVIE_GENRES
		{
			get
			{
				return ResourceManager.GetString("MOVIE_GENRES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string MOVIE_ID
		{
			get
			{
				return ResourceManager.GetString("MOVIE_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to In Theaters.
		/// </summary>
		public static string MOVIE_INTHEATERS
		{
			get
			{
				return ResourceManager.GetString("MOVIE_INTHEATERS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string MOVIE_NAME
		{
			get
			{
				return ResourceManager.GetString("MOVIE_NAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Persons.
		/// </summary>
		public static string MOVIE_PERSONS
		{
			get
			{
				return ResourceManager.GetString("MOVIE_PERSONS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Picture.
		/// </summary>
		public static string MOVIE_PICTURE
		{
			get
			{
				return ResourceManager.GetString("MOVIE_PICTURE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Picture (URL).
		/// </summary>
		public static string MOVIE_PICTUREURL
		{
			get
			{
				return ResourceManager.GetString("MOVIE_PICTUREURL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movies.
		/// </summary>
		public static string MOVIE_PLURAL
		{
			get
			{
				return ResourceManager.GetString("MOVIE_PLURAL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Released After.
		/// </summary>
		public static string MOVIE_RELEASEDAFTER
		{
			get
			{
				return ResourceManager.GetString("MOVIE_RELEASEDAFTER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Release Date.
		/// </summary>
		public static string MOVIE_RELEASEDATE
		{
			get
			{
				return ResourceManager.GetString("MOVIE_RELEASEDATE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Released Before.
		/// </summary>
		public static string MOVIE_RELEASEDBEFORE
		{
			get
			{
				return ResourceManager.GetString("MOVIE_RELEASEDBEFORE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Summary.
		/// </summary>
		public static string MOVIE_SUMMARY
		{
			get
			{
				return ResourceManager.GetString("MOVIE_SUMMARY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Trailer (URL).
		/// </summary>
		public static string MOVIE_TRAILERURL
		{
			get
			{
				return ResourceManager.GetString("MOVIE_TRAILERURL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string MOVIE_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("MOVIE_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string MOVIE_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("MOVIE_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Writers.
		/// </summary>
		public static string MOVIE_WRITERS
		{
			get
			{
				return ResourceManager.GetString("MOVIE_WRITERS", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string MOVIEGENRE_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string MOVIEGENRE_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Genre.
		/// </summary>
		public static string MOVIEGENRE_GENRE
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_GENRE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Genre Identifier.
		/// </summary>
		public static string MOVIEGENRE_GENREID
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_GENREID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string MOVIEGENRE_ID
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movie.
		/// </summary>
		public static string MOVIEGENRE_MOVIE
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_MOVIE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movie Identifier.
		/// </summary>
		public static string MOVIEGENRE_MOVIEID
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_MOVIEID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string MOVIEGENRE_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string MOVIEGENRE_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("MOVIEGENRE_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string MOVIEPERSON_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string MOVIEPERSON_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string MOVIEPERSON_ID
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movie.
		/// </summary>
		public static string MOVIEPERSON_MOVIE
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_MOVIE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movie Identifier.
		/// </summary>
		public static string MOVIEPERSON_MOVIEID
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_MOVIEID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Person.
		/// </summary>
		public static string MOVIEPERSON_PERSON
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_PERSON", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Person Identifier.
		/// </summary>
		public static string MOVIEPERSON_PERSONID
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_PERSONID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Role.
		/// </summary>
		public static string MOVIEPERSON_ROLE
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_ROLE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string MOVIEPERSON_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string MOVIEPERSON_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSON_UPDATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Actor.
		/// </summary>
		public static string MOVIEPERSONROLE_ACTOR
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSONROLE_ACTOR", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Director.
		/// </summary>
		public static string MOVIEPERSONROLE_DIRECTOR
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSONROLE_DIRECTOR", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Writer.
		/// </summary>
		public static string MOVIEPERSONROLE_WRITER
		{
			get
			{
				return ResourceManager.GetString("MOVIEPERSONROLE_WRITER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Person.
		/// </summary>
		public static string PERSON
		{
			get
			{
				return ResourceManager.GetString("PERSON", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Biography.
		/// </summary>
		public static string PERSON_BIOGRAPHY
		{
			get
			{
				return ResourceManager.GetString("PERSON_BIOGRAPHY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Birth Date.
		/// </summary>
		public static string PERSON_BIRTHDATE
		{
			get
			{
				return ResourceManager.GetString("PERSON_BIRTHDATE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Born After.
		/// </summary>
		public static string PERSON_BORNAFTER
		{
			get
			{
				return ResourceManager.GetString("PERSON_BORNAFTER", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Born Before.
		/// </summary>
		public static string PERSON_BORNBEFORE
		{
			get
			{
				return ResourceManager.GetString("PERSON_BORNBEFORE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created At.
		/// </summary>
		public static string PERSON_CREATEDAT
		{
			get
			{
				return ResourceManager.GetString("PERSON_CREATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Created By.
		/// </summary>
		public static string PERSON_CREATEDBY
		{
			get
			{
				return ResourceManager.GetString("PERSON_CREATEDBY", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Identifier.
		/// </summary>
		public static string PERSON_ID
		{
			get
			{
				return ResourceManager.GetString("PERSON_ID", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Movies.
		/// </summary>
		public static string PERSON_MOVIES
		{
			get
			{
				return ResourceManager.GetString("PERSON_MOVIES", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Name.
		/// </summary>
		public static string PERSON_NAME
		{
			get
			{
				return ResourceManager.GetString("PERSON_NAME", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Picture.
		/// </summary>
		public static string PERSON_PICTURE
		{
			get
			{
				return ResourceManager.GetString("PERSON_PICTURE", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Picture (URL).
		/// </summary>
		public static string PERSON_PICTUREURL
		{
			get
			{
				return ResourceManager.GetString("PERSON_PICTUREURL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Persons.
		/// </summary>
		public static string PERSON_PLURAL
		{
			get
			{
				return ResourceManager.GetString("PERSON_PLURAL", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated At.
		/// </summary>
		public static string PERSON_UPDATEDAT
		{
			get
			{
				return ResourceManager.GetString("PERSON_UPDATEDAT", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Updated By.
		/// </summary>
		public static string PERSON_UPDATEDBY
		{
			get
			{
				return ResourceManager.GetString("PERSON_UPDATEDBY", resourceCulture);
			}
		}
	}
}
